### ISSUE TITLE
How to change the fallback/default icon

### ISSUE THREAD

**Issue by WnndGws** [pierrechevalier83/workstyle#1]
Currently when no match for a window is found it defaults to a blank icon. Is there an easy way to specify what the fallback icon should be?

Things I have tried:

1. Adding "*" as a window name to the bottom of the config file (and various iterations of this)
2. Making simple changes to main.rs

My knowledge of rust is VERY limited so much of what I tried broke various things.

**Comment by ammgws** [comment]
@WnndGws The patterns only match whether it is a substring or not, there is no regex or wildcard support.

Try #4 and see if it works OK for you.
