### ISSUE TITLE
Renumber workspaces as windows close

### ISSUE THREAD

**Issue by WnndGws** [pierrechevalier83/workstyle#2]
I used to use [a python script](https://raw.githubusercontent.com/WnndGws/dotfiles3.0/master/dotfiles/desktop/.config/i3/i3scripts/autoname_workspaces.py) in i3, where the workspace numbers would change so that they were always in order from low to high, with no numbers missing.

eg. `1:tmux | 2:firefox | 3:vim`
closing firefox on ws2 would result in `1:tmux | 2:vim`

Workspace numbering on two monitors would also follow a [1, 2, 3], [5, 6] pattern to allow for opening a new workspace on the first monitor.

I know VERY little about rust, so the few things I have tried did not work, but I would love these features as they are the only thing I miss from i3.

**Comment by pierrechevalier83** [comment]
Personally, I rely on the workspace numbers being predictable so I can navigate to a known workspace with meta+number and use my own heuristics for which kinds of windows leave on which workspace.

I feel like this functionality may be better implemented as its own program outside of workstyle?

**Comment by pierrechevalier83** [comment]
Closing as wontfix since I don't intend to add that functionality.
