### ISSUE TITLE
Document how to enable workspace number prefix

### ISSUE THREAD

**Issue by andersfylling** [pierrechevalier83/workstyle#34]
The README.md specifies that an example setup may look like:
![image](https://user-images.githubusercontent.com/7851860/154851631-359fe11e-a7a7-409b-897f-a5e55bd78e36.png)

I would actually want this, as I don't always know the workspace number when I have multiple active workspaces. However, it's not clear to me how I can enable this workspace number prefix.

**Comment by pierrechevalier83** [comment]
In this screenshot, I'm using waybar. The workspace numbering is a setting in that tool.
https://github.com/Alexays/Waybar/wiki/Module:-Workspaces

Specifically, you will want to have
```
     "sway/workspaces": {
         ...
         "format": "{icon}",
         ...
     }
```
in `~/.config/waybar/config`
