### ISSUE TITLE
Hyprland support

### ISSUE THREAD

**Issue by cloudlena** [pierrechevalier83/workstyle#45]
Is there any plan of supporting [Hyprland](https://hyprland.org/)?

**Comment by pierrechevalier83** [comment]
I wasn't particularly planning on it, as I wasn't using Hyprland, but this motivated me to check it out and I added support in 50a6edb,

I just realized it's not going to work yet as I added a dependency on hyperland-rs and had to clone their repo locally to make it work (the last release is incompatible with the latest git version of Hyprland).

Which brings me to this point: Hyprland seems to be moving pretty fast, so support for it will be best effort and may break at anytime. I'll happily rely on PRs from people who are interested in using it to keep things in sync. I only plan to support the latest git version at any point in time.

**Comment by pierrechevalier83** [comment]
> I just realized it's not going to work yet as I added a dependency on hyperland-rs and had to clone their repo locally to make it work (the last release is incompatible with the latest git version of Hyprland).

Fixed in 03aa749c

**Comment by cloudlena** [comment]
That's awesome. Thanks for the quick reply, @pierrechevalier83!
