### ISSUE TITLE
Some icons are not properly displayed

### ISSUE THREAD

**Issue by LDAP** [pierrechevalier83/workstyle#48]
Some icons are not properly displayed in Hyprland + Waybar, instead a box containing `01F928` is drawn.

![image](https://user-images.githubusercontent.com/8215084/227496027-1719b3b3-98b8-4c47-9cc0-91771d644c44.png)

One of the icons is .

The font (Font Awesome 5 Free) is correctly configured and if I add the icon to the Waybar config directly it works just fine:
```json
"wlr/workspaces": {
  "format": "{icon}",
},
```

![image](https://user-images.githubusercontent.com/8215084/227496180-a384c5df-6d7b-4f3e-8d72-a6cc8b45a60c.png)

(The exact same config works fine on another system which has the same fonts installed.)

**Comment by krav** [comment]
Works just fine with the "Hack Nerd Font" as my only configured font-family. 
![screenshot](https://user-images.githubusercontent.com/4032/227664647-5d1ba105-a681-4c75-b9fd-5d93df5792d6.png)

**Comment by LDAP** [comment]
I fixed it by installing `ttf-dejavu` (not sure why that has anything to do with icons) and resetting the font cache with `fc-cache -vf`.

**Comment by LDAP** [comment]
Seems that this did not reliably fix it.

Running `hyprctl workspaces` shows wired workspace names too:
```
❯ hyprctl workspaces
workspace ID 2 (2: 🤨 🤨 🤨  ) on monitor eDP-1:
	windows: 4
	hasfullscreen: 1
	lastwindow: 0xec44b4f0
	lastwindowtitle: lucas: hyprctl workspaces

workspace ID 1 (1: 🤨  ) on monitor eDP-1:
	windows: 2
	hasfullscreen: 0
	lastwindow: 0xec1fbe20
	lastwindowtitle: Vorlesung
```

Expected is at least one  icon. Adding the icon directly to the Waybar config displays is correctly, it seems to me that this is an issue with workstyle.

**Comment by LDAP** [comment]
It fixed itself after a full system upgrade.
