### ISSUE TITLE
[FR] Add an option to force detection by WM_CLASS

### ISSUE THREAD

**Issue by Sonico98** [pierrechevalier83/workstyle#6]
**The problem:**
Some programs don't set their names as the window title, but instead default to the current command or file opened. Kitty, PyCharm and SpaceFM are examples of this situation. In the case of SpaceFM and Kitty, the window title can be renamed at the user's will, so it's not much of a problem, but PyCharm doesn't allow renaming the window title (which defaults to whatever file is open at the moment).

**The solution:**
Add an option to the configuration file that allows forcing the detection of windows by their class (obteinable through `xprop WM_CLASS`). It could be somewhat similar to how picom defines exceptions for specific window classes. That is:
> "firefox" = ""
> class_g("kitty") = ""
> "vim" = ""

Where kitty is being forced by its window class, instead of the current window title.

**Comment by janemba** [comment]
It doesn't work for me:
```
[...]
class_g("foot") = ""
[...]
```
lead to this error:
```
ERROR workstyle::config > Error parsing configuration file.
Invalid syntax in "/home/user/.config/workstyle/config.toml".
unexpected character found: `(` at line 33 column 8
```

**Comment by ryneeverett** [comment]
The comparable property to WM_CLASS in Wayland is "app id". Ideally app id would be supported as well.

**Comment by pierrechevalier83** [comment]
So I didn't exactly add an option to force WM_CLASS: for now, I left the config format unchanged (a map of window description to icon), but I did add support to `app_id` and `WM_CLASS`, so apps like `kitty` should work now.

https://github.com/pierrechevalier83/workstyle/commit/0395f8a47cc88aa5fb6f39592b3c341d8b61ceb1

I will close this ticket for now, as I think it addresses the intent of this issue.

@Sonico98 , @janemba , @ryneeverett , if you would actually prefer more configurability over what specifically gets matched, please let me know by raising a new issue.
