### ISSUE TITLE
Duplicate workspaces are created

### ISSUE THREAD

**Issue by hashkrish** [pierrechevalier83/workstyle#68]
Info: I am using sway

Issue: when I move the window to the current workspace (say from 4 to 4) there is a new workspace with the same number is created and I cannot switch to it.

Steps to reproduce:
1. Make a window in a workspace say 4
2. Move the current window to the same workspace say 4 (Mod4 + Shift + 4)
3. A new workspace is created

![image](https://github.com/pierrechevalier83/workstyle/assets/29514440/d5cbde36-5486-4431-948c-423b39b526b7)

**Comment by b5l** [comment]
This happens when the "move window" shortcut is configured to move a window to the workspace with **name** "4" instead of **number** "4".

My keybindings look like this:
```
    bindsym $mod+1 workspace number 1
    bindsym $mod+Ctrl+1 move container to workspace number 1
    bindsym $mod+Shift+1 move container to workspace number 1; workspace number 1
```

Note that we're calling `move container to workspace number 1` instead of `move contianer to workspace 1`.
