### ISSUE TITLE
Unknown event into hyprland-rs: workspacev2, destroyworkspacev2

### ISSUE THREAD

**Issue by badosu** [pierrechevalier83/workstyle#69]
As requested:

```
A unknown event was passed into Hyprland-rs
            PLEASE MAKE AN ISSUE!!
            The event was: workspacev2
A unknown event was passed into Hyprland-rs
            PLEASE MAKE AN ISSUE!!
            The event was: destroyworkspacev2
```

Don't have much more context than that.

**Comment by DieKautz** [comment]
This is from a dependency crate `hyprland-rs` (see [here](https://github.com/hyprland-community/hyprland-rs/blob/c0171c88897376c3c0b3032126dcfa746f69493a/src/event_listener/shared.rs#L509)).
These events should already be included there now, so the message should disappear when its version is updated in Cargo.toml

**Comment by badosu** [comment]
Alright, thank you!
